CREATE TABLE `ALARM` (
	`ARM_NO`	NUMBER	NOT NULL,
	`ARM_CONTENT`	VARCHAR2(200)	NOT NULL,
	`ARM_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`ARM_CATEGORY_NO`	NUMBER	NOT NULL
);

CREATE TABLE `FILE_DETAIL` (
	`FILE_DETAIL_NO`	NUMBER	NOT NULL,
	`FILE_NO`	NUMBER	NOT NULL,
	`FILE_SAVE_NAME`	VARCHAR2(2000)	NOT NULL,
	`FILE_ORIGIN_NAME`	VARCHAR2(2000)	NOT NULL,
	`FILE_SIZE`	VARCHAR2(50)	NOT NULL,
	`FILE_URL`	VARCHAR2(1000)	NOT NULL,
	`FILE_MIME`	VARCHAR2(30)	NOT NULL	COMMENT '미디어타입'
);

CREATE TABLE `WORKS` (
	`WORK_NO`	NUMBER	NOT NULL,
	`PRO_NO`	NUMBER	NOT NULL,
	`WORK_STATUS`	NUMBER	NOT NULL	DEFAULT 1,
	`WORK_TITLE`	VARCHAR2(300)	NOT NULL,
	`WORK_CONTENT`	VARCHAR2(3000)	NOT NULL,
	`WORK_FIRST`	VARCHAR2(30)	NOT NULL,
	`WORK_DATE`	DATE	NULL	DEFAULT SYSDATE,
	`WORK_STARTDATE`	VARCHAR2(8)	NOT NULL,
	`WORK_ENDDATE`	VARCHAR2(8)	NOT NULL,
	`WORK_PROG`	NUMBER	NOT NULL	DEFAULT 0,
	`WORK_PARENT_NO`	NUMBER	NOT NULL
);

CREATE TABLE `NOTICE` (
	`NOTICE_NO`	NUMBER	NOT NULL,
	`PROJECT_NO`	NUMBER	NOT NULL,
	`NOTICE_TITLE`	VARCHAR2(300)	NULL,
	`NOTICE_CONTENT`	VARCHAR2(500)	NULL,
	`NOTICE_DATE`	DATE	NULL	DEFAULT SYSDATE,
	`NOTICE_MODDATE`	DATE	NULL,
	`NOTICE_HIT`	NUMBER	NULL,
	`NOTICE_WRITER`	NUMBER	NULL
);

CREATE TABLE `EMPLOYEE` (
	`EMP_NO`	NUMBER	NOT NULL,
	`EMP_ID`	VARCHAR2(30)	NOT NULL,
	`POSITION_NO`	NUMBER	NOT NULL,
	`EMP_PW`	VARCHAR2(300)	NOT NULL,
	`EMP_NAME`	VARCHAR2(100)	NOT NULL,
	`EMP_PHONE`	VARCHAR2(11)	NOT NULL,
	`EMP_MAIL`	VARCHAR2(300)	NOT NULL,
	`EMP_BIRTH`	VARCHAR2(8)	NULL,
	`EMP_PROFILEIMG`	VARCHAR2(500)	NULL,
	`EMP_POSTCODE`	VARCHAR2(5)	NULL,
	`EMP_ADDRESS1`	VARCHAR2(1000)	NULL,
	`EMP_ADDRESS2`	VARCHAR2(1000)	NULL,
	`EMP_INDATE`	VARCHAR2(8)	NULL,
	`EMP_OUTDATE`	VARCHAR2(8)	NULL,
	`ENABLED`	VARCHAR2(10)	NOT NULL	DEFAULT 1,
	`EMP_FIREYN`	VARCHAR2(1)	NULL	DEFAULT 'N'
);

CREATE TABLE `MEMBERS` (
	`EMP_NO`	NUMBER	NOT NULL,
	`PRO_NO`	NUMBER	NOT NULL
);

CREATE TABLE `PROJECTS` (
	`PRO_NO`	NUMBER	NOT NULL,
	`PRO_NAME`	VARCHAR2(300)	NOT NULL,
	`PRO_CONTENT`	VARCHAR2(1000)	NOT NULL,
	`PRO_STARTDATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`PRO_ENDDATE`	DATE	NOT NULL,
	`PRO_STATUS`	NUMBER	NOT NULL	DEFAULT 1,
	`PRO_REJECT_REASON`	VARCHAR2(1000)	NULL,
	`PRO_LEADER`	NUMBER	NOT NULL
);

CREATE TABLE `CHAT` (
	`CHAT_NO`	NUMBER	NOT NULL,
	`CHATROOM_NO`	NUMBER	NOT NULL,
	`CHAT_CONTENT`	VARCHAR2(500)	NOT NULL,
	`CHAT_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`CHAT_WRITER`	NUMBER	NOT NULL
);

CREATE TABLE `VIDEO` (
	`VIDEO_ROOMNO`	NUMBER	NOT NULL,
	`VIDEO_TITLE`	VARCHAR2(30)	NOT NULL,
	`VIDEO_URL`	VARCHAR2(1000)	NULL,
	`VIDEO_STATUS`	NUMBER	NOT NULL	DEFAULT 1
);

CREATE TABLE `CHATROOM` (
	`CHATROOM_NO`	NUMBER	NOT NULL
);

CREATE TABLE `CALENDAR` (
	`ID`	NUMBER	NOT NULL,
	`EMP_NO`	NUMBER	NOT NULL,
	`TITLE`	VARCHAR2(50)	NOT NULL,
	`CONTENT`	VARCHAR2(1000)	NULL,
	`START`	DATE	NOT NULL,
	`END`	DATE	NOT NULL,
	`TEXT_COLOR`	VARCHAR2(50)	NOT NULL
);

CREATE TABLE `WORK_STATUS` (
	`WS_NO`	NUMBER	NOT NULL,
	`WS_NAME`	VARCHAR2(30)	NOT NULL
);

CREATE TABLE `WORK_COMMENT` (
	`WORK_CO_NO`	NUMBER	NOT NULL,
	`WORK_NO`	NUMBER	NOT NULL,
	`WORK_CO_WRITER`	NUMBER	NOT NULL,
	`WORK_CO_CONTENT`	VARCHAR2(200)	NOT NULL,
	`WORK_CO_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`WORK_CO_MODDATE`	DATE	NULL,
	`WORK_CO_PARENT_NO`	NUMBER	NULL
);

CREATE TABLE `EMPLOYEE_AUTH` (
	`AUTH`	VARCHAR2(20)	NOT NULL,
	`EMP_NO`	NUMBER	NOT NULL
);

CREATE TABLE `PERSISTENT_LOGINS` (
	`SERIES`	VARCHAR2(64)	NOT NULL,
	`USERNAME`	VARCHAR2(64)	NOT NULL,
	`TOKEN`	VARCHAR2(64)	NOT NULL,
	`LAST_USED`	DATE	NOT NULL
);

CREATE TABLE `CLOUD` (
	`CLOUD_NO`	NUMBER	NOT NULL,
	`FOLDER_NO`	NUMBER	NOT NULL	COMMENT '이녀석이 경로가 될거임..',
	`CLOUD_NAME`	VARCHAR2(2000)	NOT NULL,
	`CLOUD_ORIGIN_NAME`	VARCHAR2(2000)	NOT NULL,
	`CLOUD_DOWNHIT`	NUMBER	NOT NULL	DEFAULT 0,
	`CLOUD_SIZE`	NUMBER	NOT NULL,
	`CLOUD_FANCYSIZE`	VARCHAR2(50)	NOT NULL,
	`CLOUD_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`CLOUD_SAVEPATH`	VARCHAR2(1000)	NOT NULL,
	`CLOUD_MIME`	VARCHAR2(30)	NOT NULL,
	`CLOUD_WRITER`	NUMBER	NOT NULL
);

CREATE TABLE `MAIL` (
	`MAIL_NO`	NUMBER	NOT NULL,
	`MAIL_SENDER`	NUMBER	NOT NULL,
	`MAIL_RECEIVER`	NUMBER	NULL,
	`MAIL_TITLE`	VARCHAR2(200)	NOT NULL,
	`MAIL_CONTENT`	VARCHAR2(500)	NOT NULL,
	`MAIL_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`MAIL_SEND_CATEGORY`	NUMBER	NOT NULL	DEFAULT 1
);

CREATE TABLE `ISSUE` (
	`ISSUE_NO`	NUMBER	NOT NULL,
	`WORK_NO`	NUMBER	NOT NULL,
	`ISSUE_CONTENT`	VARCHAR2(500)	NOT NULL,
	`ISSUE_DATE`	DATE	NOT NULL	DEFAULT SYSDATE
);

CREATE TABLE `POSITION` (
	`POSITION_NO`	NUMBER	NOT NULL,
	`POSITION_NAME`	VARCHAR2(30)	NOT NULL
);

CREATE TABLE `ARM_CATEGORY` (
	`ARM_CATEGORY_NO`	NUMBER	NOT NULL,
	`ARM_CATEGORY_NAME`	VARCHAR2(200)	NOT NULL
);

CREATE TABLE `MANAGER` (
	`MANAGER_NO`	NUMBER	NOT NULL,
	`WORK_NO`	NUMBER	NOT NULL,
	`EMP_NO`	NUMBER	NOT NULL
);

CREATE TABLE `BOARD` (
	`BO_NO`	NUMBER	NOT NULL,
	`EMP_NO`	NUMBER	NOT NULL,
	`BO_TITLE`	VARCHAR2(200)	NOT NULL,
	`BO_CONTENT`	VARCHAR2(4000)	NOT NULL,
	`BO_HIT`	NUMBER	NOT NULL	DEFAULT 0,
	`BO_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`BO_MODDATE`	DATE	NULL,
	`BO_DELYN`	VARCHAR2(10)	NOT NULL	DEFAULT 'N'
);

CREATE TABLE `BOARD_COMMENT` (
	`BO_CO_NO`	NUMBER	NOT NULL,
	`BO_NO`	NUMBER	NOT NULL,
	`EMP_NO`	NUMBER	NOT NULL,
	`BO_CO_CONTENT`	VARCHAR2(300)	NOT NULL,
	`BO_CO_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`BO_CO_MODDATE`	DATE	NULL,
	`BO_CO_DELYN`	VARCHAR2(10)	NULL	DEFAULT 'N',
	`BO_CO_PARENT_NO`	NUMBER	NULL
);

CREATE TABLE `VIDEO_ENTRY` (
	`VIDEO_ENTRY_NO`	NUMBER	NOT NULL,
	`EMP_NO`	NUMBER	NOT NULL,
	`VIDEO_ROOMNO`	NUMBER	NOT NULL
);

CREATE TABLE `CHAT_ENTRY` (
	`CHATROOM_NO`	NUMBER	NOT NULL,
	`EMP_NO`	NUMBER	NOT NULL,
	`CHAT_STARTNO`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '몇번채팅부터 읽었는지',
	`CHAT_READNO`	NUMBER	NULL,
	`CHAT_TITLE`	VARCHAR2(1000)	NULL
);

CREATE TABLE `RECEIVE` (
	`RECEIVE_NO`	NUMBER	NOT NULL,
	`MAIL_NO`	NUMBER	NOT NULL,
	`RECEIVE_EMP`	NUMBER	NOT NULL,
	`MAIL_SENDER`	NUMBER	NOT NULL,
	`RECEIVE_CATEGORY`	NUMBER	NOT NULL	DEFAULT 1,
	`RECEIVE_READ`	NUMBER	NOT NULL	DEFAULT 1
);

CREATE TABLE `REPORT` (
	`REPORT_NO`	NUMBER	NOT NULL,
	`PRO_NO`	NUMBER	NOT NULL,
	`EMP_NO`	NUMBER	NOT NULL,
	`REPORT_TITLE`	VARCHAR2(300)	NOT NULL,
	`REPORT_CONTENT`	VARCHAR2(2000)	NOT NULL,
	`REPORT_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`REPORT_MODDATE`	DATE	NULL
);

CREATE TABLE `COMMONCODE` (
	`CC_CODE`	VARCHAR2(30)	NOT NULL,
	`CC_NAME`	VARCHAR2(50)	NULL
);

CREATE TABLE `COMMONCODEDETAIL` (
	`CCD_CODE`	VARCHAR2(30)	NOT NULL,
	`CCD_NAME`	VARCHAR2(50)	NULL,
	`CCD_CONTENT`	VARCHAR2(50)	NULL,
	`CC_CODE`	VARCHAR2(30)	NOT NULL
);

CREATE TABLE `ALARM_TO` (
	`ARM_NO`	NUMBER	NOT NULL,
	`EMP_NO`	NUMBER	NOT NULL,
	`ARM_TO_READYN`	VARCHAR2(1)	NULL	DEFAULT 'N'
);

CREATE TABLE `FILES` (
	`FILE_NO`	NUMBER	NOT NULL,
	`FILE_REGDATE`	DATE	NULL	DEFAULT SYSDATE,
	`FILE_WHERE_NO`	NUMBER	NOT NULL,
	`FILE_WHERE_PK`	NUMBER	NOT NULL
);

CREATE TABLE `FILE_WHERE` (
	`FILE_WHERE_NO`	NUMBER	NOT NULL,
	`FILE_WHERE_TITLE`	VARCHAR2(50)	NOT NULL	COMMENT '메모참고'
);

CREATE TABLE `REPORT_COMMENT` (
	`REPORT_CO_NO`	NUMBER	NOT NULL,
	`REPORT_NO`	NUMBER	NOT NULL,
	`REPORT_CO_CONTENT`	VARCHAR2(2000)	NOT NULL,
	`REPORT_CO_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`REPORT_CO_MODDATE`	DATE	NULL,
	`REPORT_CO_PARENT_NO`	NUMBER	NULL
);

CREATE TABLE `HISTORY` (
	`HISTORY_NO`	NUMBER	NOT NULL,
	`WORK_NO`	NUMBER	NOT NULL,
	`HISTORY_COLUMN`	VARCHAR2(50)	NOT NULL,
	`HISTORY_BEFORE`	VARCHAR2(500)	NOT NULL,
	`HISTORY_AFTER`	VARCHAR2(500)	NOT NULL,
	`HISTORY_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`MANAGE_NO`	NUMBER	NOT NULL
);

CREATE TABLE `FOLDER` (
	`FOLDER_NO`	NUMBER	NOT NULL,
	`PRO_NO`	NUMBER	NOT NULL,
	`FOLDER_NAME`	VARCHAR2(200)	NOT NULL,
	`PARENT_FOLDER_NO`	NUMBER	NULL
);

ALTER TABLE `ALARM` ADD CONSTRAINT `PK_ALARM` PRIMARY KEY (
	`ARM_NO`
);

ALTER TABLE `FILE_DETAIL` ADD CONSTRAINT `PK_FILE_DETAIL` PRIMARY KEY (
	`FILE_DETAIL_NO`
);

ALTER TABLE `WORKS` ADD CONSTRAINT `PK_WORKS` PRIMARY KEY (
	`WORK_NO`
);

ALTER TABLE `NOTICE` ADD CONSTRAINT `PK_NOTICE` PRIMARY KEY (
	`NOTICE_NO`
);

ALTER TABLE `EMPLOYEE` ADD CONSTRAINT `PK_EMPLOYEE` PRIMARY KEY (
	`EMP_NO`
);

ALTER TABLE `MEMBERS` ADD CONSTRAINT `PK_MEMBERS` PRIMARY KEY (
	`EMP_NO`,
	`PRO_NO`
);

ALTER TABLE `PROJECTS` ADD CONSTRAINT `PK_PROJECTS` PRIMARY KEY (
	`PRO_NO`
);

ALTER TABLE `CHAT` ADD CONSTRAINT `PK_CHAT` PRIMARY KEY (
	`CHAT_NO`
);

ALTER TABLE `VIDEO` ADD CONSTRAINT `PK_VIDEO` PRIMARY KEY (
	`VIDEO_ROOMNO`
);

ALTER TABLE `CHATROOM` ADD CONSTRAINT `PK_CHATROOM` PRIMARY KEY (
	`CHATROOM_NO`
);

ALTER TABLE `CALENDAR` ADD CONSTRAINT `PK_CALENDAR` PRIMARY KEY (
	`ID`
);

ALTER TABLE `WORK_STATUS` ADD CONSTRAINT `PK_WORK_STATUS` PRIMARY KEY (
	`WS_NO`
);

ALTER TABLE `WORK_COMMENT` ADD CONSTRAINT `PK_WORK_COMMENT` PRIMARY KEY (
	`WORK_CO_NO`
);

ALTER TABLE `PERSISTENT_LOGINS` ADD CONSTRAINT `PK_PERSISTENT_LOGINS` PRIMARY KEY (
	`SERIES`
);

ALTER TABLE `CLOUD` ADD CONSTRAINT `PK_CLOUD` PRIMARY KEY (
	`CLOUD_NO`
);

ALTER TABLE `MAIL` ADD CONSTRAINT `PK_MAIL` PRIMARY KEY (
	`MAIL_NO`
);

ALTER TABLE `ISSUE` ADD CONSTRAINT `PK_ISSUE` PRIMARY KEY (
	`ISSUE_NO`
);

ALTER TABLE `POSITION` ADD CONSTRAINT `PK_POSITION` PRIMARY KEY (
	`POSITION_NO`
);

ALTER TABLE `ARM_CATEGORY` ADD CONSTRAINT `PK_ARM_CATEGORY` PRIMARY KEY (
	`ARM_CATEGORY_NO`
);

ALTER TABLE `MANAGER` ADD CONSTRAINT `PK_MANAGER` PRIMARY KEY (
	`MANAGER_NO`
);

ALTER TABLE `BOARD` ADD CONSTRAINT `PK_BOARD` PRIMARY KEY (
	`BO_NO`
);

ALTER TABLE `BOARD_COMMENT` ADD CONSTRAINT `PK_BOARD_COMMENT` PRIMARY KEY (
	`BO_CO_NO`
);

ALTER TABLE `VIDEO_ENTRY` ADD CONSTRAINT `PK_VIDEO_ENTRY` PRIMARY KEY (
	`VIDEO_ENTRY_NO`
);

ALTER TABLE `RECEIVE` ADD CONSTRAINT `PK_RECEIVE` PRIMARY KEY (
	`RECEIVE_NO`
);

ALTER TABLE `REPORT` ADD CONSTRAINT `PK_REPORT` PRIMARY KEY (
	`REPORT_NO`
);

ALTER TABLE `COMMONCODE` ADD CONSTRAINT `PK_COMMONCODE` PRIMARY KEY (
	`CC_CODE`
);

ALTER TABLE `COMMONCODEDETAIL` ADD CONSTRAINT `PK_COMMONCODEDETAIL` PRIMARY KEY (
	`CCD_CODE`
);

ALTER TABLE `ALARM_TO` ADD CONSTRAINT `PK_ALARM_TO` PRIMARY KEY (
	`ARM_NO`,
	`EMP_NO`
);

ALTER TABLE `FILES` ADD CONSTRAINT `PK_FILES` PRIMARY KEY (
	`FILE_NO`
);

ALTER TABLE `FILE_WHERE` ADD CONSTRAINT `PK_FILE_WHERE` PRIMARY KEY (
	`FILE_WHERE_NO`
);

ALTER TABLE `REPORT_COMMENT` ADD CONSTRAINT `PK_REPORT_COMMENT` PRIMARY KEY (
	`REPORT_CO_NO`
);

ALTER TABLE `HISTORY` ADD CONSTRAINT `PK_HISTORY` PRIMARY KEY (
	`HISTORY_NO`
);

ALTER TABLE `FOLDER` ADD CONSTRAINT `PK_FOLDER` PRIMARY KEY (
	`FOLDER_NO`
);

ALTER TABLE `ALARM` ADD CONSTRAINT `FK_ARM_CATEGORY_TO_ALARM_1` FOREIGN KEY (
	`ARM_CATEGORY_NO`
)
REFERENCES `ARM_CATEGORY` (
	`ARM_CATEGORY_NO`
);

ALTER TABLE `FILE_DETAIL` ADD CONSTRAINT `FK_FILES_TO_FILE_DETAIL_1` FOREIGN KEY (
	`FILE_NO`
)
REFERENCES `FILES` (
	`FILE_NO`
);

ALTER TABLE `WORKS` ADD CONSTRAINT `FK_PROJECTS_TO_WORKS_1` FOREIGN KEY (
	`PRO_NO`
)
REFERENCES `PROJECTS` (
	`PRO_NO`
);

ALTER TABLE `WORKS` ADD CONSTRAINT `FK_WORK_STATUS_TO_WORKS_1` FOREIGN KEY (
	`WORK_STATUS`
)
REFERENCES `WORK_STATUS` (
	`WS_NO`
);

ALTER TABLE `WORKS` ADD CONSTRAINT `FK_WORKS_TO_WORKS_1` FOREIGN KEY (
	`WORK_PARENT_NO`
)
REFERENCES `WORKS` (
	`WORK_NO`
);

ALTER TABLE `NOTICE` ADD CONSTRAINT `FK_PROJECTS_TO_NOTICE_1` FOREIGN KEY (
	`PROJECT_NO`
)
REFERENCES `PROJECTS` (
	`PRO_NO`
);

ALTER TABLE `EMPLOYEE` ADD CONSTRAINT `FK_POSITION_TO_EMPLOYEE_1` FOREIGN KEY (
	`POSITION_NO`
)
REFERENCES `POSITION` (
	`POSITION_NO`
);

ALTER TABLE `MEMBERS` ADD CONSTRAINT `FK_EMPLOYEE_TO_MEMBERS_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `MEMBERS` ADD CONSTRAINT `FK_PROJECTS_TO_MEMBERS_1` FOREIGN KEY (
	`PRO_NO`
)
REFERENCES `PROJECTS` (
	`PRO_NO`
);

ALTER TABLE `PROJECTS` ADD CONSTRAINT `FK_EMPLOYEE_TO_PROJECTS_1` FOREIGN KEY (
	`PRO_LEADER`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `CHAT` ADD CONSTRAINT `FK_CHATROOM_TO_CHAT_1` FOREIGN KEY (
	`CHATROOM_NO`
)
REFERENCES `CHATROOM` (
	`CHATROOM_NO`
);

ALTER TABLE `CHAT` ADD CONSTRAINT `FK_EMPLOYEE_TO_CHAT_1` FOREIGN KEY (
	`CHAT_WRITER`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `CALENDAR` ADD CONSTRAINT `FK_EMPLOYEE_TO_CALENDAR_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `WORK_COMMENT` ADD CONSTRAINT `FK_WORKS_TO_WORK_COMMENT_1` FOREIGN KEY (
	`WORK_NO`
)
REFERENCES `WORKS` (
	`WORK_NO`
);

ALTER TABLE `WORK_COMMENT` ADD CONSTRAINT `FK_EMPLOYEE_TO_WORK_COMMENT_1` FOREIGN KEY (
	`WORK_CO_WRITER`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `WORK_COMMENT` ADD CONSTRAINT `FK_WORK_COMMENT_TO_WORK_COMMENT_1` FOREIGN KEY (
	`WORK_CO_PARENT_NO`
)
REFERENCES `WORK_COMMENT` (
	`WORK_CO_NO`
);

ALTER TABLE `EMPLOYEE_AUTH` ADD CONSTRAINT `FK_EMPLOYEE_TO_EMPLOYEE_AUTH_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `CLOUD` ADD CONSTRAINT `FK_FOLDER_TO_CLOUD_1` FOREIGN KEY (
	`FOLDER_NO`
)
REFERENCES `FOLDER` (
	`FOLDER_NO`
);

ALTER TABLE `CLOUD` ADD CONSTRAINT `FK_EMPLOYEE_TO_CLOUD_1` FOREIGN KEY (
	`CLOUD_WRITER`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `MAIL` ADD CONSTRAINT `FK_EMPLOYEE_TO_MAIL_1` FOREIGN KEY (
	`MAIL_SENDER`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `MAIL` ADD CONSTRAINT `FK_EMPLOYEE_TO_MAIL_2` FOREIGN KEY (
	`MAIL_RECEIVER`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `ISSUE` ADD CONSTRAINT `FK_WORKS_TO_ISSUE_1` FOREIGN KEY (
	`WORK_NO`
)
REFERENCES `WORKS` (
	`WORK_NO`
);

ALTER TABLE `MANAGER` ADD CONSTRAINT `FK_WORKS_TO_MANAGER_1` FOREIGN KEY (
	`WORK_NO`
)
REFERENCES `WORKS` (
	`WORK_NO`
);

ALTER TABLE `MANAGER` ADD CONSTRAINT `FK_EMPLOYEE_TO_MANAGER_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `BOARD` ADD CONSTRAINT `FK_EMPLOYEE_TO_BOARD_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `BOARD_COMMENT` ADD CONSTRAINT `FK_BOARD_TO_BOARD_COMMENT_1` FOREIGN KEY (
	`BO_NO`
)
REFERENCES `BOARD` (
	`BO_NO`
);

ALTER TABLE `BOARD_COMMENT` ADD CONSTRAINT `FK_EMPLOYEE_TO_BOARD_COMMENT_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `BOARD_COMMENT` ADD CONSTRAINT `FK_BOARD_COMMENT_TO_BOARD_COMMENT_1` FOREIGN KEY (
	`BO_CO_PARENT_NO`
)
REFERENCES `BOARD_COMMENT` (
	`BO_CO_NO`
);

ALTER TABLE `VIDEO_ENTRY` ADD CONSTRAINT `FK_EMPLOYEE_TO_VIDEO_ENTRY_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `VIDEO_ENTRY` ADD CONSTRAINT `FK_VIDEO_TO_VIDEO_ENTRY_1` FOREIGN KEY (
	`VIDEO_ROOMNO`
)
REFERENCES `VIDEO` (
	`VIDEO_ROOMNO`
);

ALTER TABLE `CHAT_ENTRY` ADD CONSTRAINT `FK_CHATROOM_TO_CHAT_ENTRY_1` FOREIGN KEY (
	`CHATROOM_NO`
)
REFERENCES `CHATROOM` (
	`CHATROOM_NO`
);

ALTER TABLE `CHAT_ENTRY` ADD CONSTRAINT `FK_EMPLOYEE_TO_CHAT_ENTRY_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `CHAT_ENTRY` ADD CONSTRAINT `FK_CHAT_TO_CHAT_ENTRY_1` FOREIGN KEY (
	`CHAT_STARTNO`
)
REFERENCES `CHAT` (
	`CHAT_NO`
);

ALTER TABLE `CHAT_ENTRY` ADD CONSTRAINT `FK_CHAT_TO_CHAT_ENTRY_2` FOREIGN KEY (
	`CHAT_READNO`
)
REFERENCES `CHAT` (
	`CHAT_NO`
);

ALTER TABLE `RECEIVE` ADD CONSTRAINT `FK_MAIL_TO_RECEIVE_1` FOREIGN KEY (
	`MAIL_NO`
)
REFERENCES `MAIL` (
	`MAIL_NO`
);

ALTER TABLE `RECEIVE` ADD CONSTRAINT `FK_EMPLOYEE_TO_RECEIVE_1` FOREIGN KEY (
	`RECEIVE_EMP`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `RECEIVE` ADD CONSTRAINT `FK_EMPLOYEE_TO_RECEIVE_2` FOREIGN KEY (
	`MAIL_SENDER`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `REPORT` ADD CONSTRAINT `FK_PROJECTS_TO_REPORT_1` FOREIGN KEY (
	`PRO_NO`
)
REFERENCES `PROJECTS` (
	`PRO_NO`
);

ALTER TABLE `REPORT` ADD CONSTRAINT `FK_EMPLOYEE_TO_REPORT_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `COMMONCODEDETAIL` ADD CONSTRAINT `FK_COMMONCODE_TO_COMMONCODEDETAIL_1` FOREIGN KEY (
	`CC_CODE`
)
REFERENCES `COMMONCODE` (
	`CC_CODE`
);

ALTER TABLE `ALARM_TO` ADD CONSTRAINT `FK_ALARM_TO_ALARM_TO_1` FOREIGN KEY (
	`ARM_NO`
)
REFERENCES `ALARM` (
	`ARM_NO`
);

ALTER TABLE `ALARM_TO` ADD CONSTRAINT `FK_EMPLOYEE_TO_ALARM_TO_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `EMPLOYEE` (
	`EMP_NO`
);

ALTER TABLE `FILES` ADD CONSTRAINT `FK_FILE_WHERE_TO_FILES_1` FOREIGN KEY (
	`FILE_WHERE_NO`
)
REFERENCES `FILE_WHERE` (
	`FILE_WHERE_NO`
);

ALTER TABLE `REPORT_COMMENT` ADD CONSTRAINT `FK_REPORT_TO_REPORT_COMMENT_1` FOREIGN KEY (
	`REPORT_NO`
)
REFERENCES `REPORT` (
	`REPORT_NO`
);

ALTER TABLE `REPORT_COMMENT` ADD CONSTRAINT `FK_REPORT_COMMENT_TO_REPORT_COMMENT_1` FOREIGN KEY (
	`REPORT_CO_PARENT_NO`
)
REFERENCES `REPORT_COMMENT` (
	`REPORT_CO_NO`
);

ALTER TABLE `HISTORY` ADD CONSTRAINT `FK_WORKS_TO_HISTORY_1` FOREIGN KEY (
	`WORK_NO`
)
REFERENCES `WORKS` (
	`WORK_NO`
);

ALTER TABLE `HISTORY` ADD CONSTRAINT `FK_MANAGER_TO_HISTORY_1` FOREIGN KEY (
	`MANAGE_NO`
)
REFERENCES `MANAGER` (
	`MANAGER_NO`
);

ALTER TABLE `FOLDER` ADD CONSTRAINT `FK_PROJECTS_TO_FOLDER_1` FOREIGN KEY (
	`PRO_NO`
)
REFERENCES `PROJECTS` (
	`PRO_NO`
);

ALTER TABLE `FOLDER` ADD CONSTRAINT `FK_FOLDER_TO_FOLDER_1` FOREIGN KEY (
	`PARENT_FOLDER_NO`
)
REFERENCES `FOLDER` (
	`FOLDER_NO`
);

